<?php 
$attributes = array('id' => 'companyForm');
echo form_open('metrics/add_metric', $attributes);
  echo '<h2 id="facilityTitle">Metric Suggestions</h2>';
  echo '<div id="innerCompanyForm">';
    echo '<div data-criteria="1">';
      echo '<h3>Environment</h3>';
      echo '<label for="Air Emissions">Air Emissions ';
        echo form_checkbox('Air Emissions', 'Air Emissions', FALSE);
      echo '</label>';
      echo '<label for="Biodiversity">Biodiversity ';
        echo form_checkbox('Biodiversity', 'Biodiversity', FALSE);
      echo '</label>';
      echo '<label for="Energy">Energy ';
        echo form_checkbox('Energy', 'Energy', FALSE);
      echo '</label>';
      echo '<label for="Greenhouse Gas Emissions">Greenhouse Gas Emissions ';
        echo form_checkbox('Greenhouse Gas Emissions', 'Greenhouse Gas Emissions', FALSE);
      echo '</label>';
      echo '<label for="Hazardous Substances">Hazardous Substances ';
        echo form_checkbox('Hazardous Substances', 'Hazardous Substances', FALSE);
      echo '</label>';
      echo '<label for="Materials">Materials ';
        echo form_checkbox('Materials', 'Materials', FALSE);
      echo '</label>';
      echo '<label for="Waste">Waste ';
        echo form_checkbox('Waste', 'Waste', FALSE);
      echo '</label>';
      echo '<label for="Water">Water ';
        echo form_checkbox('Water', 'Water', FALSE);
      echo '</label>';
    echo '</div>';
    echo '<div data-criteria="2">';
      echo '<h3>Community</h3>';
      echo '<label for="Stakeholder Engagement">Stakeholder Engagement ';
        echo form_checkbox('Stakeholder Engagement', 'Stakeholder Engagement', FALSE);
      echo '</label>';
      echo '<label for="Community Development">Community Development ';
        echo form_checkbox('Community Development', 'Community Development', FALSE);
      echo '</label>';
      echo '<label for="Philanthropy">Philanthropy ';
        echo form_checkbox('Philanthropy', 'Philanthropy', FALSE);
      echo '</label>';
      echo '<label for="Volunteerism">Volunteerism ';
        echo form_checkbox('Volunteerism', 'Volunteerism', FALSE);
      echo '</label>';
    echo '</div>';
    echo '<div data-criteria="3">';
      echo '<h3>Operating Practices</h3>';
      echo '<label for="Diversity & Equal Opportunity">Diversity & Equal Opportunity ';
        echo form_checkbox('Diversity & Equal Opportunity', 'Diversity & Equal Opportunity', FALSE);
      echo '</label>';
      echo '<label for="Employment">Employment ';
        echo form_checkbox('Employment', 'Employment', FALSE);
      echo '</label>';
      echo '<label for="Ethics">Ethics ';
        echo form_checkbox('Ethics', 'Ethics', FALSE);
      echo '</label>';
      echo '<label for="Human Rights">Human Rights ';
        echo form_checkbox('Human Rights', 'Human Rights', FALSE);
      echo '</label>';
      echo '<label for="Labor Relations">Labor Relations ';
        echo form_checkbox('Labor Relations', 'Labor Relations', FALSE);
      echo '</label>';
      echo '<label for="Occupational Health & Safety">Occupational Health & Safety ';
        echo form_checkbox('Occupational Health & Safety', 'Occupational Health & Safety', FALSE);
      echo '</label>';
      echo '<label for="Training & Education">Training & Education ';
        echo form_checkbox('Training & Education', 'Training & Education', FALSE);
      echo '</label>';
    echo '</div>';
    echo '<div data-criteria="4">';
      echo '<h3>Products & Services</h3>';
      echo '<label for="Consumer Health & Safety">Consumer Health & Safety ';
        echo form_checkbox('Consumer Health & Safety', 'Consumer Health & Safety', FALSE);
      echo '</label>';
      echo '<label for="Life Cycle Considerations">Life Cycle Considerations ';
        echo form_checkbox('Life Cycle Considerations', 'Life Cycle Considerations', FALSE);
      echo '</label>';
      echo '<label for="Responsible Sourcing">Responsible Sourcing ';
        echo form_checkbox('Responsible Sourcing', 'Responsible Sourcing', FALSE);
      echo '</label>';
      echo '<label for="Supplier Engagement">Supplier Engagement ';
        echo form_checkbox('Supplier Engagement', 'Supplier Engagement', FALSE);
      echo '</label>';
    echo '</div>';
    echo '<input id="metricSend" type="submit" name="submit" value="Submit"></input>';
  echo '</div>';
echo form_close();
?>